export interface Section {
  id: string
  title: string
  description: string
  content: string | string[]
  tasks?: string[]
}

export const sections: Section[] = [
  {
    id: "about",
    title: "About",
    description: "Personal information and overview",
    content: [
      "Hello, I'm Simon.",
      "I'm a [Your Profession] with a passion for creating elegant solutions to complex problems.",
      "With [X] years of experience in the industry, I've developed a strong foundation in [Key Skills].",
      "I believe in continuous learning and staying up-to-date with the latest technologies and best practices.",
      "My approach combines technical expertise with creative problem-solving to deliver high-quality results.",
    ],
    tasks: ["Review personal information", "Type 'skills' or 'cd skills' to continue to the next section"],
  },
  {
    id: "skills",
    title: "Skills",
    description: "Technical abilities and expertise",
    content: [
      "TECHNICAL SKILLS:",
      "• Frontend: React, Vue.js, JavaScript/TypeScript, HTML5, CSS3, Tailwind CSS",
      "• Backend: Node.js, Express, Python, Django, RESTful APIs",
      "• Database: MongoDB, PostgreSQL, MySQL, Firebase",
      "• DevOps: Docker, Kubernetes, CI/CD, AWS, Vercel",
      "• Tools: Git, GitHub, VS Code, Figma, Jira",
      "",
      "SOFT SKILLS:",
      "• Problem-solving",
      "• Team collaboration",
      "• Communication",
      "• Time management",
      "• Adaptability",
    ],
    tasks: ["Review technical and soft skills", "Type 'projects' or 'cd projects' to continue to the next section"],
  },
  {
    id: "projects",
    title: "Projects",
    description: "Portfolio of work and achievements",
    content: [
      "PROJECT 1: E-Commerce Platform",
      "• Built a full-stack e-commerce platform using React, Node.js, and MongoDB",
      "• Implemented user authentication, product catalog, and payment processing",
      "• Deployed on AWS with CI/CD pipeline",
      "• Resulted in 30% increase in conversion rate",
      "",
      "PROJECT 2: AI-Powered Analytics Dashboard",
      "• Developed a real-time analytics dashboard using Vue.js and Python",
      "• Integrated machine learning algorithms for predictive analytics",
      "• Implemented responsive design for mobile and desktop",
      "• Reduced data processing time by 40%",
      "",
      "PROJECT 3: Mobile Fitness Application",
      "• Created a cross-platform fitness app using React Native",
      "• Implemented features like workout tracking, nutrition planning, and progress visualization",
      "• Integrated with wearable devices via Bluetooth",
      "• Achieved 4.8/5 rating on app stores",
    ],
    tasks: ["Review project portfolio", "Type 'experience' or 'cd experience' to continue to the next section"],
  },
  {
    id: "experience",
    title: "Experience",
    description: "Professional work history",
    content: [
      "SENIOR DEVELOPER | ABC Tech | 2020 - Present",
      "• Lead a team of 5 developers in building and maintaining enterprise applications",
      "• Architected and implemented microservices-based infrastructure",
      "• Reduced application load time by 60% through optimization",
      "• Mentored junior developers and conducted code reviews",
      "",
      "FULL-STACK DEVELOPER | XYZ Solutions | 2017 - 2020",
      "• Developed and maintained multiple client websites and applications",
      "• Collaborated with design team to implement responsive UI/UX",
      "• Integrated third-party APIs and services",
      "• Participated in agile development process",
      "",
      "JUNIOR DEVELOPER | Tech Innovators | 2015 - 2017",
      "• Assisted in developing web applications using JavaScript and PHP",
      "• Fixed bugs and implemented new features",
      "• Participated in code reviews and team meetings",
      "• Learned and applied best practices in software development",
    ],
    tasks: ["Review work experience", "Type 'education' or 'cd education' to continue to the next section"],
  },
  {
    id: "education",
    title: "Education",
    description: "Academic background and certifications",
    content: [
      "MASTER OF SCIENCE IN COMPUTER SCIENCE",
      "University of Technology | 2013 - 2015",
      "• Specialization in Artificial Intelligence and Machine Learning",
      "• GPA: 3.8/4.0",
      "• Thesis: 'Neural Networks for Natural Language Processing'",
      "",
      "BACHELOR OF SCIENCE IN SOFTWARE ENGINEERING",
      "State University | 2009 - 2013",
      "• Minor in Mathematics",
      "• GPA: 3.7/4.0",
      "• Dean's List: All semesters",
      "",
      "CERTIFICATIONS:",
      "• AWS Certified Solutions Architect",
      "• Google Cloud Professional Developer",
      "• MongoDB Certified Developer",
      "• Certified Scrum Master",
    ],
    tasks: ["Review education and certifications", "Type 'contact' or 'cd contact' to continue to the final section"],
  },
  {
    id: "contact",
    title: "Contact",
    description: "How to get in touch",
    content: [
      "I'm always open to discussing new projects, opportunities, or partnerships.",
      "",
      "• Email: your.email@example.com",
      "• Phone: (123) 456-7890",
      "• LinkedIn: linkedin.com/in/yourname",
      "• GitHub: github.com/yourusername",
      "• Portfolio: yourportfolio.com",
      "",
      "Feel free to reach out through any of these channels. I typically respond within 24 hours.",
    ],
    tasks: [
      "Mission complete! You've unlocked all sections of the resume.",
      "Feel free to navigate between sections using the commands.",
    ],
  },
]
